import { Inter } from 'next/font/google';
import './globals.css';
import { DozersProvider } from './contexts/DozersContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <DozersProvider>
        <body className='bg-secondary-lighter min-h-screen p-24'>
          {children}
        </body>
      </DozersProvider>
    </html>
  );
}
